name: scBonita
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2024.7.2
  - pybind11-abi=5
  - python_abi=3.12
  - tzdata=2024a
  - bzip2=1.0.8
  - c-ares=1.19.1
  - jpeg=9e
  - libbrotlicommon=1.0.9
  - libdeflate=1.17
  - libexpat=2.6.2
  - libiconv=1.16
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.3.1
  - xz=5.4.6
  - icu=73.1
  - libedit=3.1.20230828
  - libevent=2.1.12
  - libffi=3.4.4
  - lz4-c=1.9.4
  - readline=8.2
  - tbb=2021.8.0
  - zlib=1.2.13
  - krb5=1.20.1
  - libpng=1.6.39
  - libxml2=2.10.4
  - pcre2=10.42
  - sqlite=3.45.3
  - tk=8.6.14
  - zstd=1.5.5
  - brotli=1.0.9
  - freetype=2.12.1
  - libtiff=4.5.1
  - libxslt=1.1.37
  - openblas
  - python=3.12.2
  - about-time=4.2.1
  - appdirs=1.4.4
  - brotli-python=1.0.9
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - colorlog=5.0.1
  - cycler=0.11.0
  - fontconfig=2.14.2
  - idna=3.7
  - joblib=1.4.2
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lxml=5.2.1
  - networkx=3.3
  - openjpeg=2.4.0
  - packaging=24.1
  - ply=3.11
  - ptyprocess=0.7.0
  - pycparser=2.22
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python-tzdata=2024.1
  - pytz=2024.1
  - setuptools=69.5.1
  - six=1.16.0
  - soupsieve=2.5
  - suds-community=1.1.2
  - threadpoolctl=3.5.0
  - tornado=6.4.1
  - unicodedata2=15.1.0
  - wheel=0.43.0
  - wrapt=1.14.1
  - xmltodict=0.13.0
  - zope=1.0
  - alive-progress=3.1.5
  - beautifulsoup4=4.12.3
  - cffi=1.16.0
  - fonttools=4.51.0
  - numpy-base=1.26.4
  - pexpect=4.9.0
  - pillow=10.4.0
  - pip=24.0
  - python-dateutil=2.9.0post0
  - tqdm=4.66.4
  - urllib3=2.2.2
  - zope.event=5.0
  - zope.interface=5.4.0
  - easydev=0.12.0
  - requests=2.32.3
  - bioservices=1.11.2
  - pyfftw
  - numpy=1.26.4
  - numexpr=2.8.7
  - scipy=1.13.1
  - pandas=2.2.2
  - scikit-learn=1.3.0
  - seaborn=0.13.2
  - fastdtw=0.3.4

  - pip:
    - deap